# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  update_type: patch

# install npm
steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

# install vsce
- powershell: |
   Write-Host "vsce setup"
   npm install vsce -g 
  displayName: 'install vsce'

# update version in package.json
- powershell: |
   Write-Host "npm version $UPDATE_TYPE"
   $package_version = (npm version $UPDATE_TYPE).toString()

- powershell: |
   Write-Host "update type is $(UPDATE_TYPE)"

# output version number (not needed)
- powershell: Write-Host "##vso[task.setvariable variable=package_version;]$package_version"
  name: outputVersion

# package extension into .vsix
- powershell: |
   Write-Host "vsce package"
   vsce package   
  displayName: 'vsce package'

# copy build from agent to artifact directory
- task: CopyFiles@2
  displayName: 'Copy Files to Artifact Directory)'
  inputs:
    Contents: |
     **\*.vsix
     **\package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# publish build in artifact directory
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
