# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  update_type: patch
  group: build_vars
  system.debug: true

steps:
- checkout: self
  persistCredentials: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true

- powershell: |
   Write-Host "vsce setup"
   npm install vsce -g 
  displayName: 'install vsce'

- powershell: |
    Write-Host "setting up git properties"
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
  displayName: "set up git properties"

- powershell: |
    git checkout master
    git add package-lock.json
    git add package.json
  displayName: "git checkout master"

- powershell: |
   Write-Host "npm version $(UPDATE_TYPE)"
   npm version
   npm version $(UPDATE_TYPE)
  displayName: 'update version field in package.json'

- powershell: |
   Write-Host "vsce package"
   vsce package   
  displayName: 'package into .vsix'

- powershell: |
    get-random > random.txt
    git add random.txt
    git status
    git show
    git commit -m "***NO_CI***"
    git push
  displayName: "push updated package.json to remote git"

- task: CopyFiles@2
  displayName: 'Copy Files to Artifact Directory)'
  inputs:
    Contents: |
     **\*.vsix
     **\package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# publish build in artifact directory
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
